# Generated by Django 4.2.7 on 2023-11-29 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discussion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_page', '0002_skilltag_topictag_userprofile_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='discussion_tags', to='user_page.topictag'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
