# Generated by Django 4.2.7 on 2023-11-29 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('user_page', '0002_skilltag_topictag_userprofile_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_page.userprofile'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='reciever',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reciever', to='user_page.userprofile'),
        ),
        migrations.AddField(
            model_name='thread',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to='user_page.userprofile'),
        ),
    ]
